version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: proe_db
    ports:
      - '1999:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: proe
    volumes:
      - ./init:/docker-entrypoint-initdb.d/